apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-pg-cluster
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      path: clusters/app1
      ref: values
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: 0.2.1
      helm:
        valueFiles:
          - $values/clusters/app1/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pg-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
