apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: "registry-1.docker.io/bitnamicharts"
      chart: kibana
      targetRevision: "11.6.0"
      helm:
        valueFiles:
          - $values/kibana/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kibana
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: kibana.local-tls
    jsonPointers:
    - /data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
