apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: gitea
spec:
  project: default
  source:
    repoURL: https://github.com/0xMNT/homelab
    targetRevision: HEAD
    path: gitea
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
