apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: gitea
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: gitea
    targetRevision: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
