apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: app1-pg-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`app1-pg-cluster.local`)
    services:
    - name: app1-pg-cluster-rw  
      namespace: app1-pg-cluster  
      port: 5432
  tls:  
    passthrough: true  
