apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 9.3.0
      helm:
        valueFiles:
          - $values/grafana/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
