
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-standalone
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 16.4.14
      helm:
        valueFiles:
          - $values/postgres-standalone/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pg-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
