# Give Kyverno the permissions it needs to create RoleBindings
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-generate-rolebindings
  annotations:
    description: "Allows Kyverno to create RoleBindings with comprehensive permissions"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-generate-rolebindings
  annotations:
    description: "Grants Kyverno background controller full permissions for generate operations"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-generate-rolebindings
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
