# Fix for Kyverno RBAC permissions
# Apply this to allow Kyverno to create RoleBindings with full permissions

# Option 1: Grant cluster-admin to Kyverno (simplest solution)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-generate-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno

---
# Alternative Option 2: More restrictive but comprehensive permissions
# Comment out the above ClusterRoleBinding and use this instead if you prefer

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: kyverno-generate-comprehensive
# rules:
# # RBAC permissions - needed to create RoleBindings
# - apiGroups: ["rbac.authorization.k8s.io"]
#   resources: ["*"]
#   verbs: ["*"]
# # Core API permissions - pods, services, secrets, etc.
# - apiGroups: [""]
#   resources: ["*"]
#   verbs: ["*"]
# # Apps permissions - deployments, replicasets, etc.
# - apiGroups: ["apps"]
#   resources: ["*"]
#   verbs: ["*"]
# # Networking permissions
# - apiGroups: ["networking.k8s.io"]
#   resources: ["*"]
#   verbs: ["*"]
# # Storage permissions
# - apiGroups: ["storage.k8s.io"]
#   resources: ["*"]
#   verbs: ["*"]
# # Batch permissions - jobs, cronjobs
# - apiGroups: ["batch"]
#   resources: ["*"]
#   verbs: ["*"]
# # Autoscaling permissions
# - apiGroups: ["autoscaling"]
#   resources: ["*"]
#   verbs: ["*"]
# # Policy permissions
# - apiGroups: ["policy"]
#   resources: ["*"]
#   verbs: ["*"]
# # Extensions permissions
# - apiGroups: ["extensions"]
#   resources: ["*"]
#   verbs: ["*"]

# ---
# # ClusterRoleBinding for the comprehensive role
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kyverno-generate-comprehensive-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: kyverno-generate-comprehensive
# subjects:
# - kind: ServiceAccount
#   name: kyverno-background-controller
#   namespace: kyverno
