apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: db-team-rbac

resources:
- 01-kyverno-rbac.yaml
- 02-db-team-rbac.yaml  
- 03-automation-policies.yaml

# Ensures resources are applied in order
generatorOptions:
  disableNameSuffixHash: true
