apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.17.1"
      helm:
        valueFiles:
          - $values/harbor/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: harbor.local-tls
    jsonPointers:
    - /data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
