apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkmk
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://checkmk.github.io/checkmk_kube_agent
      chart: checkmk
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/checkmk/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: checkmk
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
