apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      path: cnpg
      ref: values
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.23.2
      helm:
        valueFiles:
          - $values/cnpg/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
