apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: "https://helm.irsigler.cloud"
      chart: uptime-kuma
      targetRevision: "2.22.0"
      helm:
        valueFiles:
          - $values/uptime-kuma/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: uptime.local-tls
    jsonPointers:
    - /data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
