apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/0xMNT/homelab
      targetRevision: HEAD
      directory:
        recurse: true
      ref: values
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.17.1
      helm:
        valueFiles:
          - $values/cert-manager/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
