apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app2-pg-cluster
  namespace: app2-pg-cluster
spec:
  hosts:
  - "app2-pg-cluster.local"
  gateways:
  - cnpg/postgres-gateway
  tcp:
  - match:
    - sniHosts:
      - app2-pg-cluster.local
    port: 5432
    route:
    - destination:
        host: app2-pg-cluster-pooler-rw.app2-pg-cluster.svc.cluster.local # <service>.<namespace>.svc.cluster.local
        port:
          number: 5432
